project:
  type: book
  execute-dir: project

execute:
  echo: false
  warning: false

format:
  html:
    theme:
      - cosmo
    css: styles.css
  pdf:
    documentclass: report
    geometry:
      - margin=0.75in
    fig-pos: "H"
    tbl-pos: "H"
    number-sections: false
    include-in-header:
      - text: |
          \usepackage{float}
          \usepackage{titlesec}
          \titleformat{\chapter}[hang]{\Huge\bfseries}{}{0pt}{}
          \titlespacing*{\chapter}{0pt}{-30pt}{20pt}
          \floatplacement{figure}{H}
          \floatplacement{table}{H}


book:
  title: "Greenhouse Gas Inventory FY 2025"
  sidebar:
    logo: amherst_seal.png        
    style: docked                 
    background: light
  chapters:
    - index.qmd
    - part: "Municipal Inventory"
      chapters:
        - municipal/overview.qmd
        - municipal/stationary.qmd
        - municipal/transportation.qmd
        - municipal/key_findings.qmd
    - part: "Community Inventory"
      chapters:
        - community/overview.qmd
        - community/stationary.qmd        
        - community/transportation.qmd
        - community/waste.qmd
        - community/agriculture.qmd
    - final_summary.qmd
