project:
  type: book
  execute-dir: project

execute:
  echo: false
  warning: false

format:
  html:
    theme:
      - cosmo
    css: styles.css

book:
  title: "Greenhouse Gas Inventory FY 2025"
  sidebar:
    logo: amherst_seal.png        # <-- Moving it here fixes the validation error
    style: docked                 # Optional: Creates a structured background block for the menu
    background: light
  chapters:
    - index.qmd
    - part: "Municipal Inventory"
      chapters:
        - municipal/overview.qmd
        - municipal/stationary.qmd
        - municipal/transportation.qmd
    - part: "Community Inventory"
      chapters:
        - community/overview.qmd
        - community/transportation.qmd
        - community/stationary.qmd
        - community/waste.qmd
        - community/agriculture.qmd
