---
title: "Introduction"
format: html
---
## Background

The Town of Amherst Massachusetts seeks to achieve **net zero community emissions by 2050**, an ambitious goal set by the Town Council,
in the 2021 Climate Action, Adaptation, and Resilience Plan [(CAARP)](https://www.amherstma.gov/DocumentCenter/View/58981/Climate-Action-Adaptation-and-Resilience-Plan-Final-from-June-2021){.external target="_blank"}, consistent with Massachusetts State goals per the recommendation of the Energy and Climate Action Committee (ECAC). Using the 2016 emissions inventory as a baseline, the intermediary goals of **25% reduction in emissions by 2025** and **50% reduction in emissions by 2030** were set as well. 

To accurately assess progress toward the ultimate goal of carbon neutrality, periodic emissions inventories are essential for tracking emissions trends and evaluating the effectiveness of climate action initiatives. This report seeks to determine whether the Town has achieved their 2025 target, to evaluate progress toward future milestones, to identify areas of success, and to identify areas that require further intervention. 

## Progress So Far

Between 2016 and 2025, the Town made measurable progress toward its emissions reduction goals. The municipality itself, which makes up only a small fraction of community-wide emissions, has seen a 16.8% reduction in emissions since 2016. Community-wide emissions decreased by 12.9% over the same interval. While the Town's emissions reductions fell short of the 2025 target of 25%, there are a number of ongoing large-scale sustainability projects that will bring these figures down in coming years, which are discussed later in this report.

Emissions reduction often does not follow a linear path, even in cases where consistent efforts and investments are put forth. As new, sustainable, construction and renovation projects are finished, as renewable energy facilities come online, emissions will drop steeply once the data reflects these projects. With a number of such projects ongoing and nearing completion, future updates of this report will tell a more complete story of how Amherst has been progressing toward net zero emissions.


## Methodology

For purposes of consistency, the methodology of this report was kept close to that of the previous iterations of this report in 2016 and 2022, so that changes in emissions figures could be attributed to actual changes in emissions, rather than updates in methodology. Still, certain figures have been updated to reflect changes in emissions factors or to correct mistakes, though these changes have been small in scale. As carbon accounting is an evolving field, future updates to this report may be improved by updated methodologies, while keeping in mind the necessity of maintaining consistency for the integrity of comparative metrics.

### Municipal Emissions Data

Emissions and energy consumption data for the Town of Amherst Municipality comes from MassEnergyInsight (MEI), a tool managed by the Massachusetts Department of Energy Resources (DOER). This tool is routinely updated with Town fuel consumption records, and is a data source that is generally considered to be reliable.

### Community Emissions Data

Community emissions come from a variety of data sources with varying degrees of reliability. Much of the data is modeled using state-wide, or even nation-wide parameters, especially in the agriculture and waste sectors. 

## Structure of This Report

The first section of this report focuses on municipal emissions. Though municipal emissions only account for a small percentage of the community-wide total, this data is among the most actionable since the Town has direct control over its activities, and it is important that the Town leads by example in the pursuit of net zero emissions. The next section focuses on community-wide emissions, including emissions from colleges, businesses, and residents. Each section is broken down by sector, which includes stationary energy, transportation, waste, and agriculture. The report concludes with a summary of key findings and priorities going forward.
